# Generated by Django 4.2.8 on 2026-03-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_department_asset_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current calculated value after depreciation', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annual depreciation rate in percentage (e.g., 5 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when the asset was purchased', null=True),
        ),
    ]
