# Generated by Django 4.2.8 on 2026-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_asset_current_value_asset_depreciation_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original purchase cost', max_digits=12),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(default='2026-03-23', help_text='Date when the asset was purchased'),
        ),
    ]
