# Generated by Django 4.2.8 on 2026-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_asset_purchase_cost_alter_asset_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='antivirus',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Antivirus Installed', max_length=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id_auto_generated',
            field=models.BooleanField(default=True, help_text='Was asset_id automatically generated?'),
        ),
        migrations.AddField(
            model_name='asset',
            name='ccm',
            field=models.BooleanField(default=False, help_text='CCM (Configuration Management)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='corel_draw',
            field=models.BooleanField(default=False, help_text='CorelDRAW'),
        ),
        migrations.AddField(
            model_name='asset',
            name='cpu_make',
            field=models.CharField(blank=True, help_text='CPU Manufacturer (Intel, AMD, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='distiller',
            field=models.BooleanField(default=False, help_text='Distiller'),
        ),
        migrations.AddField(
            model_name='asset',
            name='e1_e3_user',
            field=models.BooleanField(default=False, help_text='E1/E3 User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='finance_asset_code',
            field=models.CharField(blank=True, help_text='Finance Asset Code', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='hdd',
            field=models.CharField(blank=True, help_text='Hard Drive/Storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, help_text='Hostname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='idm_role',
            field=models.CharField(blank=True, help_text='IDM Role', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='illustrator',
            field=models.BooleanField(default=False, help_text='Adobe Illustrator'),
        ),
        migrations.AddField(
            model_name='asset',
            name='indesign',
            field=models.BooleanField(default=False, help_text='Adobe InDesign'),
        ),
        migrations.AddField(
            model_name='asset',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Installation Date', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.CharField(blank=True, help_text='IP Address', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, help_text='Device Model', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ms_office_version',
            field=models.CharField(blank=True, choices=[('2016', 'MS Office 2016'), ('2019', 'MS Office 2019'), ('365', 'MS Office 365'), ('not_installed', 'Not Installed')], help_text='MS Office Version', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='new_hostname',
            field=models.CharField(blank=True, help_text='New Hostname', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='newswrap',
            field=models.BooleanField(default=False, help_text='Newswrap'),
        ),
        migrations.AddField(
            model_name='asset',
            name='official_email',
            field=models.EmailField(blank=True, help_text='Official Email ID', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.CharField(blank=True, choices=[('windows', 'Windows'), ('mac', 'Mac OS'), ('linux', 'Linux'), ('ubuntu', 'Ubuntu'), ('other', 'Other')], help_text='Operating System', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='photoshop',
            field=models.BooleanField(default=False, help_text='Adobe Photoshop'),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase Order Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='processor',
            field=models.CharField(blank=True, help_text='Processor Details', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram',
            field=models.CharField(blank=True, help_text='RAM (e.g., 8GB, 16GB)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks/comments', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sap_id',
            field=models.CharField(blank=True, help_text='SAP ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='srilipi',
            field=models.BooleanField(default=False, help_text='SRILIPI installed'),
        ),
        migrations.AddField(
            model_name='asset',
            name='timescale_id',
            field=models.CharField(blank=True, help_text='TimeScale ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='username',
            field=models.CharField(blank=True, help_text='Username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, help_text='Warranty Expiry Date', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('repair', 'Under Repair'), ('retired', 'Retired'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
