# Generated by Django 4.2.8 on 2026-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_asset_antivirus_asset_asset_id_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='os',
            field=models.TextField(blank=True, help_text='Operating System (detailed version info)', null=True),
        ),
    ]
