# Generated by Django 4.2.8 on 2026-04-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_asset_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ms_office_version',
            field=models.TextField(blank=True, help_text='MS Office Version (e.g., MICROSOFT-OFFICE VERSION-7, MICROSOFT-OFFICE VERSION-O365)', null=True),
        ),
    ]
