# Generated by Django 4.2.8 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_asset_ms_office_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ccm',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='e1_e3_user',
        ),
        migrations.AddField(
            model_name='asset',
            name='e1_user',
            field=models.BooleanField(default=False, help_text='E1 User'),
        ),
        migrations.AddField(
            model_name='asset',
            name='e3_user',
            field=models.BooleanField(default=False, help_text='E3 User'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='processor',
            field=models.TextField(blank=True, help_text='Processor Details (e.g., Intel Core i7-12700K, AMD Ryzen 9 5950X)', null=True),
        ),
    ]
