# Generated by Django 4.2.8 on 2026-04-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_asset_ccm_remove_asset_e1_e3_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='new_hostname',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='timescale_id',
        ),
    ]
